services:
  cctv:
    image: ${REGISTRY_URL}/mo-cctv/cctv:latest
    build:
      context: .
      dockerfile: deploy/docker/cctv/Dockerfile
    environment:
      - RTSP_URL_1=${RTSP_URL_1}
      - CAMERA_PREFIX_1=${CAMERA_PREFIX_1}
      - SEGMENT_TIME=${SEGMENT_TIME}
      - HOURS_TO_KEEP=${HOURS_TO_KEEP}
      - TZ=Asia/Yekaterinburg
    volumes:
      - ${RECORDS_PATH}:/records
      - ./nginx/.htpasswd:/etc/nginx/.htpasswd:ro
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
    networks:
      - traefik-public

networks:
  traefik-public:
    external: true
