services:
  recorder:
    image: lscr.io/linuxserver/ffmpeg:latest
    container_name: cctv-recorder
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Yekaterinburg #Europe/Moscow
    user: "1000:1000"
    volumes:
      - ./records:/records
      - ./scripts:/scripts
    command: [
      "-timeout", "5000000",
      "-rtsp_transport", "tcp",
      "-i", "rtsp://192.168.0.121:554/0/av1",
      "-c:v", "copy",
      "-c:a", "aac", "-b:a", "32k", "-ac", "1",
      "-f", "segment",
      "-segment_time", "300",
      "-segment_format", "mp4",
      "-reset_timestamps", "1",
      "-strftime", "1",
      "-avoid_negative_ts", "make_non_negative",
      "/records/elevatorLobby_%Y-%m-%d_%H-%M-%S.mp4"
    ]

  cleanup:
    image: alpine:latest
    container_name: cctv-cleanup
    restart: unless-stopped
    user: "1000:1000"
    volumes:
      - ./records:/records
      - ./scripts:/scripts
    command: sh -c "while true; do /scripts/cleanup.sh; sleep 3600; done"

  web:
    image: nginx:alpine
    container_name: cctv-web
    restart: unless-stopped
    ports:
      - "8888:80"
    user: "1000:1000"
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./records:/usr/share/nginx/html/records
      - ./web:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/cache:/var/cache/nginx
      - ./nginx/temp:/var/run
    depends_on:
      - recorder